application:
  project: "KryptLok"
  env: "dev"
  contact_email: "info@ophelios.com"
  locales:
    - fr_CA

locale:
  currency: "CAD"
  timezone: "America/Montreal"
  language: "fr_CA"
  charset: "utf8"
  format_date: "d LLLL yyyy"
  format_time: "HH:mm"
  format_datetime: "d LLLL yyyy, HH:mm"

mailer:
  transport: "smtp"
  from_address: !php/const MAIL_FROM
  from_name: !php/const MAIL_FROM_NAME
  smtp:
    enabled: true
    host: !php/const MAIL_HOST
    port: !php/const MAIL_PORT
    encryption: "none"
    username: ""
    password: ""

database:
  hostname: !php/const DB_HOSTNAME
  username: !php/const DB_USERNAME
  password: !php/const DB_PASSWORD
  database: !php/const DB_NAME
  search_paths:
    - public

render:
  engine: "latte"
  cache_update: !php/const CACHE_UPDATE

session:
  storage: "database"
  table: "public.session"
  encrypted: true
  lifetime: 1440

security:
  password:
    pepper: !php/const PASSWORD_PEPPER
  encryption:
    key: !php/const ENCRYPTION_KEY
  csrf:
    enabled: true
  ids:
    enabled: true
    impact_threshold: 50
  mfa:
    mfa_expiration_seconds: !php/const MFA_EXPIRATION_SECONDS
    otp_expiration_seconds: !php/const OTP_EXPIRATION_SECONDS
    mfa_grace_period_days: !php/const MFA_GRACE_PERIOD_DAYS

twilio:
  account_sid: !php/const TWILIO_ACCOUNT_SID
  auth_token: !php/const TWILIO_AUTH_TOKEN
  phone_from: !php/const TWILIO_PHONE_FROM
